---
# tasks file for dotfiles
- copy:
    src: "{{ item }}"
    dest: "{{ dotfiles_home}}/.{{ item }}"
    mode: 0644
    backup: yes
  with_items:
    - "{{ dotfiles_files_local }}"

# ensure directories exist
- file:
    path: "{{ dotfiles_home}}/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ dotfiles_dirs_local }}"
    