set nocompatible
set number

syntax on

" Softtabs, 2 spaces
set tabstop=2
set shiftwidth=2
set shiftround
set expandtab

" Display extra whitespace
set list listchars=tab:»·,trail:·

" Color scheme
colorscheme desert
highlight NonText guibg=#060606
highlight Folded  guibg=#0A0A0A guifg=#9090D0